# Generated by Django 5.2.3 on 2025-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('occasion', models.CharField(choices=[('anniversary', 'Anniversary'), ('birthday', 'Birthday')], default='other', max_length=20)),
            ],
        ),
    ]
