# Generated by Django 5.2.3 on 2025-06-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_booking_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='Guest', max_length=255),
        ),
    ]
