# Generated by Django 5.2.3 on 2025-06-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_booking_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.CharField(choices=[('anniversary', 'Anniversary'), ('Birthday', 'Birthday')], default='birthday', max_length=20),
        ),
    ]
